# Nome do projeto dbt
name: 'CertificacaoAE2025'
version: '1.0.0'
config-version: 2

# Configuração do perfil
profile: 'default'

# Definição dos caminhos dos arquivos
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Diretório de saída dos modelos compilados
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuração dos modelos dbt
models:
  CertificacaoAE2025:
    staging:
      +database: FEA24_11
      +schema: stg_cert25
      +materialized: view

    intermediate:
      +database: FEA24_11
      +schema: int_cert25
      +materialized: view

    marts:
      +database: FEA24_11
      +schema: marts_cert25
      +materialized: table
